### ISSUE TITLE
Unable to further test path of Polyline

### ISSUE THREAD

**Issue by TomasRM2112** [googlemaps/js-jest-mocks#224] opened 2022-03-17 10:34 UTC
It is not possible to test functions of polyline path because of line https://github.com/googlemaps/js-jest-mocks/blob/main/src/drawing/polygons/polyline.ts#L33 which makes the `getPath()` return to be an empty object `{}` instead of instance of `MVCArray`

example
```
const mockLatLng = new google.maps.LatLng(-1, 1);

const polyLine = new google.maps.Polyline();            
const path = polyLine.getPath();
path.push(mockLatLng);

expect(polyLine.getPath).toHaveBeenCalled();
expect(path.push).toHaveBeenCalledWith(mockLatLng);
```

**Comment by jpoehnelt** [comment] 2022-03-17 10:34
@TomasRM2112 Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by jpoehnelt** [comment] 2022-03-17 10:35
@TomasRM2112 Please take a moment to fill out [this short survey](https://forms.gle/wYuzN6UibnFj7ZL29). Thank you!

_This is an automated message, feel free to ignore._

**Comment by jpoehnelt** [comment] 2022-03-17 16:06
> which makes the getPath() return to be an empty object {} instead of instance of MVCArray

seems like this should be fixed. want to submit a pr?

**Comment by TomasRM2112** [comment] 2022-03-21 09:50
A bit swamped at the moment, but will do over the weekend 👍

**Comment by usefulthink** [comment] 2023-09-29 11:25
duplicate of #345.

**Closed by usefulthink** 2023-09-29 11:25 UTC
Labels: status: duplicate
